-- =====================================================
-- COMPREHENSIVE DATABASE COMMENTS IMPLEMENTATION
-- Adding detailed comments for all tables and fields
-- Generated: July 29, 2025
-- =====================================================

-- Users Table Comments
COMMENT ON TABLE users IS 'System users with authentication and role-based access control';
COMMENT ON COLUMN users.id IS 'Unique identifier for each user';
COMMENT ON COLUMN users.username IS 'Unique username for login authentication';
COMMENT ON COLUMN users.password IS 'Encrypted password hash for secure authentication';
COMMENT ON COLUMN users.email IS 'User email address for notifications and communication';
COMMENT ON COLUMN users.roles IS 'Bitmask representing user roles and permissions';
COMMENT ON COLUMN users.created_at IS 'Timestamp when user account was created';
COMMENT ON COLUMN users.updated_at IS 'Timestamp of last user account modification';

-- Account Info Table Comments
COMMENT ON TABLE account_info IS 'Company account information and subscription details';
COMMENT ON COLUMN account_info.id IS 'Unique identifier for account information record';
COMMENT ON COLUMN account_info.user_id IS 'Reference to the primary user for this account';
COMMENT ON COLUMN account_info.company_name IS 'Name of the company or organization';
COMMENT ON COLUMN account_info.subscription_plan IS 'Current subscription plan (starter, pro, enterprise)';
COMMENT ON COLUMN account_info.subscription_status IS 'Current subscription status (trial, active, expired)';
COMMENT ON COLUMN account_info.current_users IS 'Number of active users in the account';
COMMENT ON COLUMN account_info.max_users IS 'Maximum allowed users for current subscription';
COMMENT ON COLUMN account_info.billing_cycle IS 'Billing cycle frequency (monthly, yearly)';
COMMENT ON COLUMN account_info.next_billing_date IS 'Next scheduled billing date';

-- User Preferences Table Comments
COMMENT ON TABLE user_preferences IS 'Individual user interface and system preferences';
COMMENT ON COLUMN user_preferences.id IS 'Unique identifier for user preferences record';
COMMENT ON COLUMN user_preferences.user_id IS 'Reference to the user who owns these preferences';
COMMENT ON COLUMN user_preferences.theme IS 'UI theme preference (light, dark, auto)';
COMMENT ON COLUMN user_preferences.notifications_enabled IS 'Whether notifications are enabled for this user';
COMMENT ON COLUMN user_preferences.language IS 'Preferred language for user interface';
COMMENT ON COLUMN user_preferences.timezone IS 'User timezone for date/time display';
COMMENT ON COLUMN user_preferences.default_plant_id IS 'Default manufacturing plant for user operations';

-- Onboarding Status Table Comments
COMMENT ON TABLE onboarding_status IS 'User onboarding progress and completion tracking';
COMMENT ON COLUMN onboarding_status.id IS 'Unique identifier for onboarding status record';
COMMENT ON COLUMN onboarding_status.company_name IS 'Company name provided during onboarding';
COMMENT ON COLUMN onboarding_status.industry IS 'Industry type (pharmaceutical, chemical, automotive, etc.)';
COMMENT ON COLUMN onboarding_status.size IS 'Company size classification (startup, small, medium, enterprise)';
COMMENT ON COLUMN onboarding_status.description IS 'Company description or additional details';
COMMENT ON COLUMN onboarding_status.current_step IS 'Current step in onboarding process';
COMMENT ON COLUMN onboarding_status.completed_steps IS 'Array of completed onboarding steps';
COMMENT ON COLUMN onboarding_status.selected_features IS 'Array of features selected during onboarding';
COMMENT ON COLUMN onboarding_status.team_members IS 'Number of team members to be added';
COMMENT ON COLUMN onboarding_status.is_completed IS 'Whether onboarding process is fully completed';
COMMENT ON COLUMN onboarding_status.created_by IS 'User who initiated the onboarding process';
COMMENT ON COLUMN onboarding_status.created_at IS 'Timestamp when onboarding was started';
COMMENT ON COLUMN onboarding_status.updated_at IS 'Timestamp of last onboarding status update';

-- Plants Table Comments
COMMENT ON TABLE plants IS 'Manufacturing facilities and production locations';
COMMENT ON COLUMN plants.id IS 'Unique identifier for each manufacturing plant';
COMMENT ON COLUMN plants.plant_code IS 'Unique code identifier for the plant';
COMMENT ON COLUMN plants.plant_name IS 'Descriptive name of the manufacturing plant';
COMMENT ON COLUMN plants.location IS 'Physical location or address of the plant';
COMMENT ON COLUMN plants.manager IS 'Plant manager or responsible person';
COMMENT ON COLUMN plants.capacity IS 'Maximum production capacity of the plant';
COMMENT ON COLUMN plants.status IS 'Current operational status (active, inactive, maintenance)';
COMMENT ON COLUMN plants.created_at IS 'Timestamp when plant record was created';
COMMENT ON COLUMN plants.updated_at IS 'Timestamp of last plant record modification';

-- Departments Table Comments
COMMENT ON TABLE departments IS 'Organizational departments within manufacturing plants';
COMMENT ON COLUMN departments.id IS 'Unique identifier for each department';
COMMENT ON COLUMN departments.plant_id IS 'Reference to the plant containing this department';
COMMENT ON COLUMN departments.department_code IS 'Unique code identifier for the department';
COMMENT ON COLUMN departments.department_name IS 'Descriptive name of the department';
COMMENT ON COLUMN departments.department_type IS 'Type of department (production, quality, maintenance, etc.)';
COMMENT ON COLUMN departments.manager IS 'Department manager or supervisor';
COMMENT ON COLUMN departments.cost_center IS 'Cost center code for financial tracking';
COMMENT ON COLUMN departments.is_active IS 'Whether the department is currently active';
COMMENT ON COLUMN departments.created_at IS 'Timestamp when department record was created';
COMMENT ON COLUMN departments.updated_at IS 'Timestamp of last department record modification';

-- Work Centers Table Comments
COMMENT ON TABLE work_centers IS 'Manufacturing work centers and production stations';
COMMENT ON COLUMN work_centers.id IS 'Unique identifier for each work center';
COMMENT ON COLUMN work_centers.department_id IS 'Reference to the department containing this work center';
COMMENT ON COLUMN work_centers.work_center_code IS 'Unique code identifier for the work center';
COMMENT ON COLUMN work_centers.work_center_name IS 'Descriptive name of the work center';
COMMENT ON COLUMN work_centers.work_center_type IS 'Type of work center (machine, assembly, inspection, etc.)';
COMMENT ON COLUMN work_centers.capacity IS 'Maximum production capacity of the work center';
COMMENT ON COLUMN work_centers.efficiency IS 'Current efficiency percentage of the work center';
COMMENT ON COLUMN work_centers.cost_per_hour IS 'Hourly cost for using this work center';
COMMENT ON COLUMN work_centers.setup_time IS 'Standard setup time in minutes';
COMMENT ON COLUMN work_centers.queue_time IS 'Standard queue time in minutes';
COMMENT ON COLUMN work_centers.is_active IS 'Whether the work center is currently active';
COMMENT ON COLUMN work_centers.created_at IS 'Timestamp when work center record was created';
COMMENT ON COLUMN work_centers.updated_at IS 'Timestamp of last work center record modification';

-- Resources Table Comments
COMMENT ON TABLE resources IS 'Manufacturing resources including equipment, machines, and tools';
COMMENT ON COLUMN resources.id IS 'Unique identifier for each resource';
COMMENT ON COLUMN resources.name IS 'Descriptive name of the resource';
COMMENT ON COLUMN resources.type IS 'Type of resource (machine, equipment, tool, labor, etc.)';
COMMENT ON COLUMN resources.description IS 'Detailed description of the resource';
COMMENT ON COLUMN resources.capacity IS 'Maximum capacity or throughput of the resource';
COMMENT ON COLUMN resources.unit_of_measure IS 'Unit of measure for capacity (units/hour, kg/hour, etc.)';
COMMENT ON COLUMN resources.cost_per_hour IS 'Hourly cost for using this resource';
COMMENT ON COLUMN resources.efficiency IS 'Current efficiency percentage of the resource';
COMMENT ON COLUMN resources.availability IS 'Availability percentage (considering maintenance, etc.)';
COMMENT ON COLUMN resources.location IS 'Physical location of the resource';
COMMENT ON COLUMN resources.status IS 'Current status (available, busy, maintenance, down)';
COMMENT ON COLUMN resources.created_at IS 'Timestamp when resource record was created';
COMMENT ON COLUMN resources.updated_at IS 'Timestamp of last resource record modification';

-- Capabilities Table Comments
COMMENT ON TABLE capabilities IS 'Manufacturing capabilities and skills that resources can perform';
COMMENT ON COLUMN capabilities.id IS 'Unique identifier for each capability';
COMMENT ON COLUMN capabilities.name IS 'Name of the manufacturing capability';
COMMENT ON COLUMN capabilities.description IS 'Detailed description of the capability';
COMMENT ON COLUMN capabilities.category IS 'Category of capability (machining, assembly, testing, etc.)';
COMMENT ON COLUMN capabilities.skill_level IS 'Required skill level (basic, intermediate, advanced, expert)';
COMMENT ON COLUMN capabilities.certification_required IS 'Whether certification is required for this capability';
COMMENT ON COLUMN capabilities.created_at IS 'Timestamp when capability record was created';
COMMENT ON COLUMN capabilities.updated_at IS 'Timestamp of last capability record modification';

-- Resource Capabilities Junction Table Comments
COMMENT ON TABLE resource_capabilities IS 'Many-to-many relationship between resources and their capabilities';
COMMENT ON COLUMN resource_capabilities.id IS 'Unique identifier for the resource-capability relationship';
COMMENT ON COLUMN resource_capabilities.resource_id IS 'Reference to the resource';
COMMENT ON COLUMN resource_capabilities.capability_id IS 'Reference to the capability';
COMMENT ON COLUMN resource_capabilities.proficiency_level IS 'Proficiency level of resource in this capability';
COMMENT ON COLUMN resource_capabilities.certification_date IS 'Date when certification was obtained';
COMMENT ON COLUMN resource_capabilities.expiration_date IS 'Date when certification expires';
COMMENT ON COLUMN resource_capabilities.created_at IS 'Timestamp when relationship was established';
COMMENT ON COLUMN resource_capabilities.updated_at IS 'Timestamp of last relationship modification';

-- Work Center Resources Junction Table Comments
COMMENT ON TABLE work_center_resources IS 'Assignment of resources to work centers with allocation details';
COMMENT ON COLUMN work_center_resources.id IS 'Unique identifier for the work center-resource assignment';
COMMENT ON COLUMN work_center_resources.work_center_id IS 'Reference to the work center';
COMMENT ON COLUMN work_center_resources.resource_id IS 'Reference to the resource';
COMMENT ON COLUMN work_center_resources.allocation_percentage IS 'Percentage of resource allocated to this work center';
COMMENT ON COLUMN work_center_resources.cost_allocation_method IS 'Method for allocating costs (direct, overhead, shared)';
COMMENT ON COLUMN work_center_resources.effective_date IS 'Date when allocation becomes effective';
COMMENT ON COLUMN work_center_resources.end_date IS 'Date when allocation ends (if applicable)';
COMMENT ON COLUMN work_center_resources.is_primary IS 'Whether this is the primary assignment for the resource';
COMMENT ON COLUMN work_center_resources.created_at IS 'Timestamp when assignment was created';
COMMENT ON COLUMN work_center_resources.updated_at IS 'Timestamp of last assignment modification';

-- Department Resources Junction Table Comments
COMMENT ON TABLE department_resources IS 'Assignment of resources to departments with allocation details';
COMMENT ON COLUMN department_resources.id IS 'Unique identifier for the department-resource assignment';
COMMENT ON COLUMN department_resources.department_id IS 'Reference to the department';
COMMENT ON COLUMN department_resources.resource_id IS 'Reference to the resource';
COMMENT ON COLUMN department_resources.allocation_percentage IS 'Percentage of resource allocated to this department';
COMMENT ON COLUMN department_resources.cost_allocation_method IS 'Method for allocating costs (direct, overhead, shared)';
COMMENT ON COLUMN department_resources.effective_date IS 'Date when allocation becomes effective';
COMMENT ON COLUMN department_resources.end_date IS 'Date when allocation ends (if applicable)';
COMMENT ON COLUMN department_resources.is_primary IS 'Whether this is the primary assignment for the resource';
COMMENT ON COLUMN department_resources.created_at IS 'Timestamp when assignment was created';
COMMENT ON COLUMN department_resources.updated_at IS 'Timestamp of last assignment modification';

-- Items Table Comments
COMMENT ON TABLE items IS 'Master data for all manufactured and purchased items';
COMMENT ON COLUMN items.id IS 'Unique identifier for each item';
COMMENT ON COLUMN items.item_number IS 'Unique item number or SKU';
COMMENT ON COLUMN items.item_name IS 'Descriptive name of the item';
COMMENT ON COLUMN items.description IS 'Detailed description of the item';
COMMENT ON COLUMN items.item_type IS 'Type of item (raw_material, semi_finished, finished_good, service)';
COMMENT ON COLUMN items.category IS 'Category classification of the item';
COMMENT ON COLUMN items.unit_of_measure IS 'Primary unit of measure for the item';
COMMENT ON COLUMN items.standard_cost IS 'Standard cost per unit of the item';
COMMENT ON COLUMN items.last_cost IS 'Most recent actual cost per unit';
COMMENT ON COLUMN items.average_cost IS 'Average cost per unit over time';
COMMENT ON COLUMN items.target_margin IS 'Target profit margin percentage';
COMMENT ON COLUMN items.reorder_point IS 'Inventory level that triggers reordering';
COMMENT ON COLUMN items.minimum_stock IS 'Minimum stock level to maintain';
COMMENT ON COLUMN items.maximum_stock IS 'Maximum stock level to maintain';
COMMENT ON COLUMN items.economic_order_quantity IS 'Optimal order quantity for procurement';
COMMENT ON COLUMN items.minimum_order_quantity IS 'Minimum quantity required for ordering';
COMMENT ON COLUMN items.order_multiple IS 'Quantity multiple for ordering (e.g., must order in dozens)';
COMMENT ON COLUMN items.abc_classification IS 'ABC classification based on usage/value analysis';
COMMENT ON COLUMN items.xyz_classification IS 'XYZ classification based on demand variability';
COMMENT ON COLUMN items.annual_usage IS 'Annual usage quantity for planning purposes';
COMMENT ON COLUMN items.demand_variability IS 'Measure of demand variability for inventory planning';
COMMENT ON COLUMN items.lead_time IS 'Standard lead time for procurement in days';
COMMENT ON COLUMN items.safety_stock IS 'Safety stock quantity to buffer against uncertainty';
COMMENT ON COLUMN items.quality_grade IS 'Quality grade or classification of the item';
COMMENT ON COLUMN items.requires_inspection IS 'Whether incoming items require quality inspection';
COMMENT ON COLUMN items.hazardous_material IS 'Whether item is classified as hazardous material';
COMMENT ON COLUMN items.regulatory_class IS 'Regulatory classification (pharmaceutical, chemical, etc.)';
COMMENT ON COLUMN items.un_code IS 'UN code for hazardous materials';
COMMENT ON COLUMN items.cas_number IS 'Chemical Abstracts Service registry number';
COMMENT ON COLUMN items.storage_conditions IS 'Required storage conditions (temperature, humidity, etc.)';
COMMENT ON COLUMN items.shelf_life IS 'Shelf life in days for perishable items';
COMMENT ON COLUMN items.preferred_vendor_id IS 'Reference to preferred supplier';
COMMENT ON COLUMN items.source_type IS 'Source type (buy, make, transfer)';
COMMENT ON COLUMN items.buyer_code IS 'Code identifying the responsible buyer';
COMMENT ON COLUMN items.sourcing_strategy IS 'Sourcing strategy (single, multiple, spot_buy)';
COMMENT ON COLUMN items.make_vs_buy_decision IS 'Make vs buy decision (make, buy, either)';
COMMENT ON COLUMN items.lifecycle_stage IS 'Product lifecycle stage (development, active, obsolete)';
COMMENT ON COLUMN items.phase_out_date IS 'Planned phase-out date for obsolete items';
COMMENT ON COLUMN items.replacement_item_id IS 'Reference to replacement item if being phased out';
COMMENT ON COLUMN items.revision_level IS 'Current revision level of the item';
COMMENT ON COLUMN items.release_date IS 'Date when item was released for use';
COMMENT ON COLUMN items.planning_method IS 'Planning method (MRP, reorder_point, JIT)';
COMMENT ON COLUMN items.planning_horizon IS 'Planning horizon in days';
COMMENT ON COLUMN items.consumption_method IS 'How consumption is recorded (backflush, pick_list)';
COMMENT ON COLUMN items.backflush_flag IS 'Whether item is backflushed during production';
COMMENT ON COLUMN items.phantom_flag IS 'Whether item is a phantom (pass-through) item';
COMMENT ON COLUMN items.critical_component IS 'Whether item is critical for production';
COMMENT ON COLUMN items.alternate_unit_of_measure IS 'Alternate unit of measure for ordering';
COMMENT ON COLUMN items.conversion_factor IS 'Conversion factor between primary and alternate UOM';
COMMENT ON COLUMN items.dimensions IS 'Physical dimensions (length, width, height, weight)';
COMMENT ON COLUMN items.product_family IS 'Product family grouping';
COMMENT ON COLUMN items.planner_code IS 'Code identifying the responsible planner';
COMMENT ON COLUMN items.commodity_code IS 'Commodity code for procurement classification';
COMMENT ON COLUMN items.hts_code IS 'Harmonized Tariff Schedule code for international trade';
COMMENT ON COLUMN items.country_of_origin IS 'Country where item is manufactured';
COMMENT ON COLUMN items.created_by IS 'User who created the item record';
COMMENT ON COLUMN items.last_modified_by IS 'User who last modified the item record';
COMMENT ON COLUMN items.last_modified_date IS 'Timestamp of last modification';
COMMENT ON COLUMN items.last_count_date IS 'Date of last physical inventory count';
COMMENT ON COLUMN items.last_usage_date IS 'Date of last usage or transaction';
COMMENT ON COLUMN items.is_active IS 'Whether the item is currently active';
COMMENT ON COLUMN items.created_at IS 'Timestamp when item record was created';
COMMENT ON COLUMN items.updated_at IS 'Timestamp of last item record modification';

-- Production Orders Table Comments
COMMENT ON TABLE production_orders IS 'Manufacturing production orders for discrete and process manufacturing';
COMMENT ON COLUMN production_orders.id IS 'Unique identifier for each production order';
COMMENT ON COLUMN production_orders.order_number IS 'Unique production order number';
COMMENT ON COLUMN production_orders.product_id IS 'Reference to the product being manufactured';
COMMENT ON COLUMN production_orders.quantity IS 'Quantity to be produced';
COMMENT ON COLUMN production_orders.unit_of_measure IS 'Unit of measure for production quantity';
COMMENT ON COLUMN production_orders.status IS 'Current status (planned, released, started, completed, closed)';
COMMENT ON COLUMN production_orders.priority IS 'Production priority level (low, normal, high, urgent)';
COMMENT ON COLUMN production_orders.scheduled_start_date IS 'Planned start date for production';
COMMENT ON COLUMN production_orders.scheduled_end_date IS 'Planned completion date for production';
COMMENT ON COLUMN production_orders.actual_start_date IS 'Actual production start date';
COMMENT ON COLUMN production_orders.actual_end_date IS 'Actual production completion date';
COMMENT ON COLUMN production_orders.plant_id IS 'Reference to manufacturing plant';
COMMENT ON COLUMN production_orders.customer_id IS 'Reference to customer for make-to-order production';
COMMENT ON COLUMN production_orders.parent_order_id IS 'Reference to parent order for split/consolidated orders';
COMMENT ON COLUMN production_orders.order_category IS 'Order category (normal, rework, prototype, sample)';
COMMENT ON COLUMN production_orders.wip_value IS 'Current work-in-process value';
COMMENT ON COLUMN production_orders.actual_labor_hours IS 'Actual labor hours consumed';
COMMENT ON COLUMN production_orders.actual_material_cost IS 'Actual material cost incurred';
COMMENT ON COLUMN production_orders.actual_overhead_cost IS 'Actual overhead cost allocated';
COMMENT ON COLUMN production_orders.standard_cost IS 'Standard cost for the production order';
COMMENT ON COLUMN production_orders.cost_variance IS 'Variance between actual and standard cost';
COMMENT ON COLUMN production_orders.labor_rate_variance IS 'Labor rate variance analysis';
COMMENT ON COLUMN production_orders.material_price_variance IS 'Material price variance analysis';
COMMENT ON COLUMN production_orders.yield_quantity IS 'Actual yield quantity produced';
COMMENT ON COLUMN production_orders.scrap_quantity IS 'Quantity scrapped during production';
COMMENT ON COLUMN production_orders.rework_quantity IS 'Quantity requiring rework';
COMMENT ON COLUMN production_orders.good_quantity IS 'Good quality quantity produced';
COMMENT ON COLUMN production_orders.yield_percentage IS 'Yield percentage achieved';
COMMENT ON COLUMN production_orders.scrap_percentage IS 'Scrap percentage incurred';
COMMENT ON COLUMN production_orders.rework_percentage IS 'Rework percentage required';
COMMENT ON COLUMN production_orders.setup_time_planned IS 'Planned setup time in minutes';
COMMENT ON COLUMN production_orders.setup_time_actual IS 'Actual setup time in minutes';
COMMENT ON COLUMN production_orders.run_time_planned IS 'Planned run time in minutes';
COMMENT ON COLUMN production_orders.run_time_actual IS 'Actual run time in minutes';
COMMENT ON COLUMN production_orders.cleanup_time_planned IS 'Planned cleanup time in minutes';
COMMENT ON COLUMN production_orders.cleanup_time_actual IS 'Actual cleanup time in minutes';
COMMENT ON COLUMN production_orders.total_time_planned IS 'Total planned time in minutes';
COMMENT ON COLUMN production_orders.total_time_actual IS 'Total actual time in minutes';
COMMENT ON COLUMN production_orders.batch_number IS 'Batch number for traceability';
COMMENT ON COLUMN production_orders.lot_number IS 'Lot number for traceability';
COMMENT ON COLUMN production_orders.campaign_number IS 'Campaign number for batch processing';
COMMENT ON COLUMN production_orders.production_line IS 'Production line identifier';
COMMENT ON COLUMN production_orders.shift_number IS 'Shift during which production occurred';
COMMENT ON COLUMN production_orders.operator_id IS 'Reference to production operator';
COMMENT ON COLUMN production_orders.supervisor_id IS 'Reference to production supervisor';
COMMENT ON COLUMN production_orders.equipment_used IS 'Equipment used in production';
COMMENT ON COLUMN production_orders.completion_percentage IS 'Percentage of production completed';
COMMENT ON COLUMN production_orders.last_operation_completed IS 'Last operation completed';
COMMENT ON COLUMN production_orders.next_operation_due IS 'Next operation scheduled';
COMMENT ON COLUMN production_orders.bottleneck_resource IS 'Current bottleneck resource';
COMMENT ON COLUMN production_orders.downtime_minutes IS 'Downtime minutes experienced';
COMMENT ON COLUMN production_orders.efficiency_percentage IS 'Production efficiency achieved';
COMMENT ON COLUMN production_orders.oee_percentage IS 'Overall Equipment Effectiveness percentage';
COMMENT ON COLUMN production_orders.first_pass_yield IS 'First pass yield percentage';
COMMENT ON COLUMN production_orders.inspection_status IS 'Quality inspection status';
COMMENT ON COLUMN production_orders.certificate_of_analysis IS 'Certificate of analysis document';
COMMENT ON COLUMN production_orders.deviation_reports IS 'Production deviation reports';
COMMENT ON COLUMN production_orders.corrective_actions IS 'Corrective actions taken';
COMMENT ON COLUMN production_orders.batch_record_complete IS 'Whether batch record is complete';
COMMENT ON COLUMN production_orders.release_approved IS 'Whether product release is approved';
COMMENT ON COLUMN production_orders.notes IS 'Additional notes and comments';
COMMENT ON COLUMN production_orders.created_at IS 'Timestamp when production order was created';
COMMENT ON COLUMN production_orders.updated_at IS 'Timestamp of last production order modification';

-- Sales Orders Table Comments
COMMENT ON TABLE sales_orders IS 'Customer sales orders with comprehensive pricing and terms';
COMMENT ON COLUMN sales_orders.id IS 'Unique identifier for each sales order';
COMMENT ON COLUMN sales_orders.order_number IS 'Unique sales order number';
COMMENT ON COLUMN sales_orders.customer_id IS 'Reference to customer placing the order';
COMMENT ON COLUMN sales_orders.order_date IS 'Date when order was placed';
COMMENT ON COLUMN sales_orders.requested_delivery_date IS 'Customer requested delivery date';
COMMENT ON COLUMN sales_orders.promised_delivery_date IS 'Promised delivery date to customer';
COMMENT ON COLUMN sales_orders.expected_delivery_date IS 'Expected delivery date based on planning';
COMMENT ON COLUMN sales_orders.status IS 'Order status (draft, confirmed, shipped, delivered, closed)';
COMMENT ON COLUMN sales_orders.priority IS 'Order priority level (low, normal, high, urgent)';
COMMENT ON COLUMN sales_orders.sales_person IS 'Sales person responsible for the order';
COMMENT ON COLUMN sales_orders.subtotal IS 'Subtotal amount before discounts and taxes';
COMMENT ON COLUMN sales_orders.discount_amount IS 'Total discount amount applied';
COMMENT ON COLUMN sales_orders.discount_percentage IS 'Discount percentage applied';
COMMENT ON COLUMN sales_orders.tax_amount IS 'Total tax amount';
COMMENT ON COLUMN sales_orders.freight_amount IS 'Freight/shipping amount';
COMMENT ON COLUMN sales_orders.total_amount IS 'Total order amount including all charges';
COMMENT ON COLUMN sales_orders.payment_terms IS 'Payment terms (NET30, 2/10NET30, COD, etc.)';
COMMENT ON COLUMN sales_orders.payment_method IS 'Payment method (trade_credit, ACH, credit_card)';
COMMENT ON COLUMN sales_orders.credit_limit IS 'Customer credit limit';
COMMENT ON COLUMN sales_orders.credit_check_required IS 'Whether credit check is required';
COMMENT ON COLUMN sales_orders.credit_approved IS 'Whether credit has been approved';
COMMENT ON COLUMN sales_orders.credit_approved_date IS 'Date when credit was approved';
COMMENT ON COLUMN sales_orders.shipping_terms IS 'Shipping terms (FOB Origin, FOB Destination, EXW, DDP)';
COMMENT ON COLUMN sales_orders.carrier_code IS 'Shipping carrier code (UPS, FedEx, DHL, etc.)';
COMMENT ON COLUMN sales_orders.shipping_method IS 'Shipping method (ground, air, express)';
COMMENT ON COLUMN sales_orders.freight_terms IS 'Freight terms (Prepaid, Collect, Third_Party)';
COMMENT ON COLUMN sales_orders.sales_channel IS 'Sales channel (direct, distributor, online, retail)';
COMMENT ON COLUMN sales_orders.sales_territory IS 'Sales territory code';
COMMENT ON COLUMN sales_orders.sales_region IS 'Sales region code';
COMMENT ON COLUMN sales_orders.commission_rate IS 'Commission rate percentage';
COMMENT ON COLUMN sales_orders.commission_amount IS 'Commission amount calculated';
COMMENT ON COLUMN sales_orders.discount_codes IS 'Array of discount codes applied';
COMMENT ON COLUMN sales_orders.volume_discount_tier IS 'Volume discount tier (bronze, silver, gold, platinum)';
COMMENT ON COLUMN sales_orders.loyalty_discount IS 'Loyalty discount percentage';
COMMENT ON COLUMN sales_orders.seasonal_discount IS 'Seasonal discount percentage';
COMMENT ON COLUMN sales_orders.early_payment_discount IS 'Early payment discount percentage';
COMMENT ON COLUMN sales_orders.tax_exempt IS 'Whether order is tax exempt';
COMMENT ON COLUMN sales_orders.tax_exempt_certificate IS 'Tax exemption certificate number';
COMMENT ON COLUMN sales_orders.tax_jurisdiction IS 'Tax jurisdiction code';
COMMENT ON COLUMN sales_orders.sales_tax_rate IS 'Sales tax rate applied';
COMMENT ON COLUMN sales_orders.use_tax_rate IS 'Use tax rate applied';
COMMENT ON COLUMN sales_orders.vat_rate IS 'VAT rate for international orders';
COMMENT ON COLUMN sales_orders.tax_calculation_method IS 'Tax calculation method (standard, vertex, avalara)';
COMMENT ON COLUMN sales_orders.contract_number IS 'Associated contract number';
COMMENT ON COLUMN sales_orders.price_list_id IS 'Price list used for pricing';
COMMENT ON COLUMN sales_orders.quotation_number IS 'Related quotation number';
COMMENT ON COLUMN sales_orders.quotation_valid_until IS 'Quotation validity date';
COMMENT ON COLUMN sales_orders.price_hold_until IS 'Price hold date';
COMMENT ON COLUMN sales_orders.incoterms IS 'International commercial terms (EXW, FOB, CIF, DDP)';
COMMENT ON COLUMN sales_orders.export_license IS 'Export license number if required';
COMMENT ON COLUMN sales_orders.import_license IS 'Import license number if required';
COMMENT ON COLUMN sales_orders.country_of_origin IS 'Country of origin for products';
COMMENT ON COLUMN sales_orders.harmonized_code IS 'Harmonized tariff code';
COMMENT ON COLUMN sales_orders.customs_value IS 'Customs value for international shipments';
COMMENT ON COLUMN sales_orders.requires_approval IS 'Whether order requires approval';
COMMENT ON COLUMN sales_orders.approval_required IS 'Type of approval required';
COMMENT ON COLUMN sales_orders.approved_by IS 'User who approved the order';
COMMENT ON COLUMN sales_orders.approved_date IS 'Date when order was approved';
COMMENT ON COLUMN sales_orders.approval_notes IS 'Notes related to approval process';
COMMENT ON COLUMN sales_orders.shipping_address IS 'Shipping address details';
COMMENT ON COLUMN sales_orders.billing_address IS 'Billing address details';
COMMENT ON COLUMN sales_orders.special_instructions IS 'Special shipping or handling instructions';
COMMENT ON COLUMN sales_orders.notes IS 'Additional order notes';
COMMENT ON COLUMN sales_orders.created_at IS 'Timestamp when sales order was created';
COMMENT ON COLUMN sales_orders.updated_at IS 'Timestamp of last sales order modification';

-- Stocks Table Comments
COMMENT ON TABLE stocks IS 'Inventory stock levels and tracking by location and item';
COMMENT ON COLUMN stocks.id IS 'Unique identifier for each stock record';
COMMENT ON COLUMN stocks.item_id IS 'Reference to the item being tracked';
COMMENT ON COLUMN stocks.storage_location_id IS 'Reference to storage location';
COMMENT ON COLUMN stocks.quantity_on_hand IS 'Current quantity available in stock';
COMMENT ON COLUMN stocks.quantity_reserved IS 'Quantity reserved for orders';
COMMENT ON COLUMN stocks.quantity_available IS 'Available quantity (on hand - reserved)';
COMMENT ON COLUMN stocks.allocated_quantity IS 'Quantity allocated for planned orders';
COMMENT ON COLUMN stocks.in_transit_quantity IS 'Quantity in transit between locations';
COMMENT ON COLUMN stocks.unit_cost IS 'Current unit cost of stock';
COMMENT ON COLUMN stocks.total_value IS 'Total value of stock (quantity × unit cost)';
COMMENT ON COLUMN stocks.cost_method IS 'Costing method (FIFO, LIFO, average)';
COMMENT ON COLUMN stocks.last_count_variance IS 'Variance from last cycle count';
COMMENT ON COLUMN stocks.minimum_level IS 'Minimum stock level threshold';
COMMENT ON COLUMN stocks.maximum_level IS 'Maximum stock level threshold';
COMMENT ON COLUMN stocks.reorder_point IS 'Reorder point for automatic replenishment';
COMMENT ON COLUMN stocks.lot_number IS 'Lot number for batch tracking';
COMMENT ON COLUMN stocks.serial_number IS 'Serial number for individual item tracking';
COMMENT ON COLUMN stocks.expiry_date IS 'Expiration date for perishable items';
COMMENT ON COLUMN stocks.last_movement_date IS 'Date of last stock movement';
COMMENT ON COLUMN stocks.last_count_date IS 'Date of last physical count';
COMMENT ON COLUMN stocks.is_quarantined IS 'Whether stock is quarantined';
COMMENT ON COLUMN stocks.quality_status IS 'Quality status (approved, rejected, pending)';
COMMENT ON COLUMN stocks.created_at IS 'Timestamp when stock record was created';
COMMENT ON COLUMN stocks.updated_at IS 'Timestamp of last stock record modification';

-- Bills of Material Table Comments
COMMENT ON TABLE bills_of_material IS 'Bills of material for discrete manufacturing products';
COMMENT ON COLUMN bills_of_material.id IS 'Unique identifier for each BOM';
COMMENT ON COLUMN bills_of_material.bom_number IS 'Unique BOM number';
COMMENT ON COLUMN bills_of_material.product_id IS 'Reference to the product this BOM produces';
COMMENT ON COLUMN bills_of_material.version IS 'BOM version number';
COMMENT ON COLUMN bills_of_material.status IS 'BOM status (draft, active, inactive, obsolete)';
COMMENT ON COLUMN bills_of_material.effective_date IS 'Date when BOM becomes effective';
COMMENT ON COLUMN bills_of_material.obsolete_date IS 'Date when BOM becomes obsolete';
COMMENT ON COLUMN bills_of_material.base_quantity IS 'Base quantity for BOM calculations';
COMMENT ON COLUMN bills_of_material.unit_of_measure IS 'Unit of measure for base quantity';
COMMENT ON COLUMN bills_of_material.scrap_factor IS 'Scrap factor percentage for materials';
COMMENT ON COLUMN bills_of_material.yield_factor IS 'Expected yield factor percentage';
COMMENT ON COLUMN bills_of_material.alternate_items IS 'JSON array of alternate component items';
COMMENT ON COLUMN bills_of_material.engineering_change_number IS 'Engineering change order number';
COMMENT ON COLUMN bills_of_material.description IS 'Description of the BOM';
COMMENT ON COLUMN bills_of_material.notes IS 'Additional notes about the BOM';
COMMENT ON COLUMN bills_of_material.created_by IS 'User who created the BOM';
COMMENT ON COLUMN bills_of_material.approved_by IS 'User who approved the BOM';
COMMENT ON COLUMN bills_of_material.approved_date IS 'Date when BOM was approved';
COMMENT ON COLUMN bills_of_material.created_at IS 'Timestamp when BOM was created';
COMMENT ON COLUMN bills_of_material.updated_at IS 'Timestamp of last BOM modification';

-- Vendors Table Comments
COMMENT ON TABLE vendors IS 'Supplier and vendor master data with comprehensive management information';
COMMENT ON COLUMN vendors.id IS 'Unique identifier for each vendor';
COMMENT ON COLUMN vendors.vendor_code IS 'Unique vendor code or number';
COMMENT ON COLUMN vendors.vendor_name IS 'Official vendor company name';
COMMENT ON COLUMN vendors.vendor_type IS 'Type of vendor (supplier, service_provider, contractor)';
COMMENT ON COLUMN vendors.category IS 'Vendor category (strategic, preferred, standard)';
COMMENT ON COLUMN vendors.strategic_importance IS 'Strategic importance level (critical, high, medium, low)';
COMMENT ON COLUMN vendors.contact_person IS 'Primary contact person at vendor';
COMMENT ON COLUMN vendors.phone_number IS 'Primary phone number';
COMMENT ON COLUMN vendors.email IS 'Primary email address';
COMMENT ON COLUMN vendors.website IS 'Vendor website URL';
COMMENT ON COLUMN vendors.address IS 'Physical address details';
COMMENT ON COLUMN vendors.geographic_region IS 'Geographic region classification';
COMMENT ON COLUMN vendors.time_zone IS 'Vendor time zone';
COMMENT ON COLUMN vendors.payment_terms IS 'Standard payment terms';
COMMENT ON COLUMN vendors.credit_limit IS 'Credit limit for purchases';
COMMENT ON COLUMN vendors.currency IS 'Default currency for transactions';
COMMENT ON COLUMN vendors.incoterms IS 'Preferred international commercial terms';
COMMENT ON COLUMN vendors.freight_terms IS 'Standard freight terms';
COMMENT ON COLUMN vendors.pricing_terms IS 'Pricing structure and terms';
COMMENT ON COLUMN vendors.banking_information IS 'Banking details for payments';
COMMENT ON COLUMN vendors.tax_id IS 'Tax identification number';
COMMENT ON COLUMN vendors.lead_time_days IS 'Standard lead time in days';
COMMENT ON COLUMN vendors.minimum_order_amount IS 'Minimum order amount required';
COMMENT ON COLUMN vendors.maximum_order_amount IS 'Maximum order amount allowed';
COMMENT ON COLUMN vendors.shipping_method IS 'Preferred shipping method';
COMMENT ON COLUMN vendors.drop_ship_capable IS 'Whether vendor can drop ship';
COMMENT ON COLUMN vendors.consignment_eligible IS 'Whether eligible for consignment';
COMMENT ON COLUMN vendors.vmi_capable IS 'Vendor managed inventory capability';
COMMENT ON COLUMN vendors.edi_capable IS 'Electronic data interchange capability';
COMMENT ON COLUMN vendors.contract_start_date IS 'Contract start date';
COMMENT ON COLUMN vendors.contract_end_date IS 'Contract end date';
COMMENT ON COLUMN vendors.contract_type IS 'Type of contract (blanket, spot, framework)';
COMMENT ON COLUMN vendors.blanket_po_eligible IS 'Eligible for blanket purchase orders';
COMMENT ON COLUMN vendors.quality_rating IS 'Quality performance rating (1-5)';
COMMENT ON COLUMN vendors.delivery_rating IS 'Delivery performance rating (1-5)';
COMMENT ON COLUMN vendors.service_rating IS 'Service performance rating (1-5)';
COMMENT ON COLUMN vendors.overall_rating IS 'Overall vendor rating (1-5)';
COMMENT ON COLUMN vendors.last_audit_date IS 'Date of last vendor audit';
COMMENT ON COLUMN vendors.next_audit_date IS 'Scheduled next audit date';
COMMENT ON COLUMN vendors.certifications IS 'Array of vendor certifications';
COMMENT ON COLUMN vendors.regulatory_certifications IS 'Regulatory certifications (ISO, FDA, EPA)';
COMMENT ON COLUMN vendors.risk_level IS 'Risk assessment level (low, medium, high, critical)';
COMMENT ON COLUMN vendors.risk_factors IS 'Identified risk factors';
COMMENT ON COLUMN vendors.insurance_requirements IS 'Required insurance coverage';
COMMENT ON COLUMN vendors.business_continuity_plan IS 'Business continuity plan status';
COMMENT ON COLUMN vendors.backup_vendor_id IS 'Reference to backup vendor';
COMMENT ON COLUMN vendors.spend_category IS 'Spend category classification';
COMMENT ON COLUMN vendors.annual_spend IS 'Annual spend amount with vendor';
COMMENT ON COLUMN vendors.diversity_classification IS 'Diversity classification (small, minority, woman, veteran)';
COMMENT ON COLUMN vendors.small_business IS 'Small business certification status';
COMMENT ON COLUMN vendors.minority_owned IS 'Minority-owned business status';
COMMENT ON COLUMN vendors.woman_owned IS 'Woman-owned business status';
COMMENT ON COLUMN vendors.veteran_owned IS 'Veteran-owned business status';
COMMENT ON COLUMN vendors.disadvantaged_business IS 'Disadvantaged business status';
COMMENT ON COLUMN vendors.social_responsibility_rating IS 'Social responsibility rating';
COMMENT ON COLUMN vendors.environmental_rating IS 'Environmental performance rating';
COMMENT ON COLUMN vendors.sustainability_initiatives IS 'Sustainability initiatives and programs';
COMMENT ON COLUMN vendors.supplier_capabilities IS 'Description of supplier capabilities';
COMMENT ON COLUMN vendors.capacity_constraints IS 'Known capacity constraints';
COMMENT ON COLUMN vendors.technology_capabilities IS 'Technology and system capabilities';
COMMENT ON COLUMN vendors.quality_certifications IS 'Quality management certifications';
COMMENT ON COLUMN vendors.preferred_communication_method IS 'Preferred communication method';
COMMENT ON COLUMN vendors.escalation_contacts IS 'Escalation contact information';
COMMENT ON COLUMN vendors.performance_metrics IS 'Key performance metrics tracked';
COMMENT ON COLUMN vendors.improvement_initiatives IS 'Ongoing improvement initiatives';
COMMENT ON COLUMN vendors.contract_terms IS 'Key contract terms and conditions';
COMMENT ON COLUMN vendors.sla_requirements IS 'Service level agreement requirements';
COMMENT ON COLUMN vendors.status IS 'Vendor status (active, inactive, blocked, prospective)';
COMMENT ON COLUMN vendors.created_by IS 'User who created the vendor record';
COMMENT ON COLUMN vendors.last_modified_by IS 'User who last modified the vendor record';
COMMENT ON COLUMN vendors.last_modified_date IS 'Date of last modification';
COMMENT ON COLUMN vendors.last_order_date IS 'Date of last purchase order';
COMMENT ON COLUMN vendors.created_at IS 'Timestamp when vendor record was created';
COMMENT ON COLUMN vendors.updated_at IS 'Timestamp of last vendor record modification';

-- Inventory Transactions Table Comments
COMMENT ON TABLE inventory_transactions IS 'Complete audit trail for all inventory movements and transactions';
COMMENT ON COLUMN inventory_transactions.id IS 'Unique identifier for each inventory transaction';
COMMENT ON COLUMN inventory_transactions.transaction_number IS 'Unique transaction number for reference';
COMMENT ON COLUMN inventory_transactions.item_id IS 'Reference to the item being transacted';
COMMENT ON COLUMN inventory_transactions.storage_location_id IS 'Reference to storage location';
COMMENT ON COLUMN inventory_transactions.transaction_type IS 'Type of transaction (receipt, issue, adjustment, transfer, etc.)';
COMMENT ON COLUMN inventory_transactions.transaction_date IS 'Date when transaction occurred';
COMMENT ON COLUMN inventory_transactions.posting_date IS 'Date when transaction was posted to system';
COMMENT ON COLUMN inventory_transactions.reference_document_type IS 'Type of reference document (PO, SO, WO, TO)';
COMMENT ON COLUMN inventory_transactions.reference_document_number IS 'Reference document number';
COMMENT ON COLUMN inventory_transactions.reference_document_line IS 'Reference document line number';
COMMENT ON COLUMN inventory_transactions.quantity_before IS 'Quantity before transaction';
COMMENT ON COLUMN inventory_transactions.quantity_change IS 'Quantity change (positive or negative)';
COMMENT ON COLUMN inventory_transactions.quantity_after IS 'Quantity after transaction';
COMMENT ON COLUMN inventory_transactions.unit_of_measure IS 'Unit of measure for quantities';
COMMENT ON COLUMN inventory_transactions.unit_cost IS 'Unit cost at time of transaction';
COMMENT ON COLUMN inventory_transactions.total_cost IS 'Total cost of transaction';
COMMENT ON COLUMN inventory_transactions.cost_center IS 'Cost center charged for transaction';
COMMENT ON COLUMN inventory_transactions.gl_account IS 'General ledger account affected';
COMMENT ON COLUMN inventory_transactions.lot_number IS 'Lot number for batch tracking';
COMMENT ON COLUMN inventory_transactions.serial_number IS 'Serial number for individual tracking';
COMMENT ON COLUMN inventory_transactions.expiry_date IS 'Expiry date for perishable items';
COMMENT ON COLUMN inventory_transactions.from_location_id IS 'Source location for transfers';
COMMENT ON COLUMN inventory_transactions.to_location_id IS 'Destination location for transfers';
COMMENT ON COLUMN inventory_transactions.reason_code IS 'Reason code for transaction';
COMMENT ON COLUMN inventory_transactions.reason_description IS 'Detailed reason description';
COMMENT ON COLUMN inventory_transactions.quality_status IS 'Quality status (quarantine, released, rejected, expired)';
COMMENT ON COLUMN inventory_transactions.created_by IS 'User who created the transaction';
COMMENT ON COLUMN inventory_transactions.approved_by IS 'User who approved the transaction';
COMMENT ON COLUMN inventory_transactions.approved_date IS 'Date when transaction was approved';
COMMENT ON COLUMN inventory_transactions.source_system IS 'Source system (ERP, WMS, MES)';
COMMENT ON COLUMN inventory_transactions.batch_id IS 'Batch identifier for grouped transactions';
COMMENT ON COLUMN inventory_transactions.reversal_reference_id IS 'Reference to reversal transaction if applicable';
COMMENT ON COLUMN inventory_transactions.tags IS 'Array of tags for categorization';
COMMENT ON COLUMN inventory_transactions.notes IS 'Additional transaction notes';
COMMENT ON COLUMN inventory_transactions.created_at IS 'Timestamp when transaction was created';
COMMENT ON COLUMN inventory_transactions.updated_at IS 'Timestamp of last transaction modification';

-- Continue with additional critical manufacturing tables...
-- This provides comprehensive documentation for the core tables
-- Additional tables can be documented following the same pattern