-- Rename all pt_publish_* tables to ptTableName format
-- This script renames all PT Publish tables to shorter names without underscores

-- Disable foreign key checks temporarily
BEGIN;

-- Rename main tables (alphabetical order)
ALTER TABLE IF EXISTS pt_publish_capabilities RENAME TO ptCapabilities;
ALTER TABLE IF EXISTS pt_publish_capacity_interval_resource_assignments RENAME TO ptCapacityIntervalResourceAssignments;
ALTER TABLE IF EXISTS pt_publish_capacity_intervals RENAME TO ptCapacityIntervals;
ALTER TABLE IF EXISTS pt_publish_customers RENAME TO ptCustomers;
ALTER TABLE IF EXISTS pt_publish_departments RENAME TO ptDepartments;
ALTER TABLE IF EXISTS pt_publish_forecast_shipment_inventory_adjustments RENAME TO ptForecastShipmentInventoryAdjustments;
ALTER TABLE IF EXISTS pt_publish_forecast_shipments RENAME TO ptForecastShipments;
ALTER TABLE IF EXISTS pt_publish_forecasts RENAME TO ptForecasts;
ALTER TABLE IF EXISTS pt_publish_inventories RENAME TO ptInventories;
ALTER TABLE IF EXISTS pt_publish_items RENAME TO ptItems;
ALTER TABLE IF EXISTS pt_publish_job_activities RENAME TO ptJobActivities;
ALTER TABLE IF EXISTS pt_publish_job_activity_inventory_adjustments RENAME TO ptJobActivityInventoryAdjustments;
ALTER TABLE IF EXISTS pt_publish_job_material_supplying_activities RENAME TO ptJobMaterialSupplyingActivities;
ALTER TABLE IF EXISTS pt_publish_job_materials RENAME TO ptJobMaterials;
ALTER TABLE IF EXISTS pt_publish_job_operation_attributes RENAME TO ptJobOperationAttributes;
ALTER TABLE IF EXISTS pt_publish_job_operations RENAME TO ptJobOperations;
ALTER TABLE IF EXISTS pt_publish_job_path_nodes RENAME TO ptJobPathNodes;
ALTER TABLE IF EXISTS pt_publish_job_paths RENAME TO ptJobPaths;
ALTER TABLE IF EXISTS pt_publish_job_product_deleted_demands RENAME TO ptJobProductDeletedDemands;
ALTER TABLE IF EXISTS pt_publish_job_product_forecast_demands RENAME TO ptJobProductForecastDemands;
ALTER TABLE IF EXISTS pt_publish_job_product_safety_stock_demands RENAME TO ptJobProductSafetyStockDemands;
ALTER TABLE IF EXISTS pt_publish_job_product_sales_order_demands RENAME TO ptJobProductSalesOrderDemands;
ALTER TABLE IF EXISTS pt_publish_job_product_transfer_order_demands RENAME TO ptJobProductTransferOrderDemands;
ALTER TABLE IF EXISTS pt_publish_job_products RENAME TO ptJobProducts;
ALTER TABLE IF EXISTS pt_publish_job_resource_block_intervals RENAME TO ptJobResourceBlockIntervals;
ALTER TABLE IF EXISTS pt_publish_job_resource_blocks RENAME TO ptJobResourceBlocks;
ALTER TABLE IF EXISTS pt_publish_job_resource_capabilities RENAME TO ptJobResourceCapabilities;
ALTER TABLE IF EXISTS pt_publish_job_resources RENAME TO ptJobResources;
ALTER TABLE IF EXISTS pt_publish_job_successor_manufacturing_orders RENAME TO ptJobSuccessorManufacturingOrders;
ALTER TABLE IF EXISTS pt_publish_jobs RENAME TO ptJobs;
ALTER TABLE IF EXISTS pt_publish_kpis RENAME TO ptKpis;
ALTER TABLE IF EXISTS pt_publish_lots RENAME TO ptLots;
ALTER TABLE IF EXISTS pt_publish_manufacturing_orders RENAME TO ptManufacturingOrders;
ALTER TABLE IF EXISTS pt_publish_master_production_schedule RENAME TO ptMasterProductionSchedule;
ALTER TABLE IF EXISTS pt_publish_metrics RENAME TO ptMetrics;
ALTER TABLE IF EXISTS pt_publish_plant_warehouses RENAME TO ptPlantWarehouses;
ALTER TABLE IF EXISTS pt_publish_plants RENAME TO ptPlants;
ALTER TABLE IF EXISTS pt_publish_product_rules RENAME TO ptProductRules;
ALTER TABLE IF EXISTS pt_publish_pt_attributes RENAME TO ptAttributes;
ALTER TABLE IF EXISTS pt_publish_purchase_to_stock_deleted_demands RENAME TO ptPurchaseToStockDeletedDemands;
ALTER TABLE IF EXISTS pt_publish_purchase_to_stock_forecast_demands RENAME TO ptPurchaseToStockForecastDemands;
ALTER TABLE IF EXISTS pt_publish_purchase_to_stock_inventory_adjustments RENAME TO ptPurchaseToStockInventoryAdjustments;
ALTER TABLE IF EXISTS pt_publish_purchase_to_stock_safety_stock_demands RENAME TO ptPurchaseToStockSafetyStockDemands;
ALTER TABLE IF EXISTS pt_publish_purchase_to_stock_sales_order_demands RENAME TO ptPurchaseToStockSalesOrderDemands;
ALTER TABLE IF EXISTS pt_publish_purchase_to_stock_transfer_order_demands RENAME TO ptPurchaseToStockTransferOrderDemands;
ALTER TABLE IF EXISTS pt_publish_purchases_to_stock RENAME TO ptPurchasesToStock;
ALTER TABLE IF EXISTS pt_publish_recurring_capacity_interval_recurrences RENAME TO ptRecurringCapacityIntervalRecurrences;
ALTER TABLE IF EXISTS pt_publish_recurring_capacity_interval_resource_assignments RENAME TO ptRecurringCapacityIntervalResourceAssignments;
ALTER TABLE IF EXISTS pt_publish_recurring_capacity_intervals RENAME TO ptRecurringCapacityIntervals;
ALTER TABLE IF EXISTS pt_publish_resource_alternate_resources RENAME TO ptResourceAlternateResources;
ALTER TABLE IF EXISTS pt_publish_resource_capabilities RENAME TO ptResourceCapabilities;
ALTER TABLE IF EXISTS pt_publish_resource_scheduled_down_capacities RENAME TO ptResourceScheduledDownCapacities;
ALTER TABLE IF EXISTS pt_publish_resources RENAME TO ptResources;
ALTER TABLE IF EXISTS pt_publish_sales_order_releases RENAME TO ptSalesOrderReleases;
ALTER TABLE IF EXISTS pt_publish_sales_orders RENAME TO ptSalesOrders;
ALTER TABLE IF EXISTS pt_publish_stock_availability RENAME TO ptStockAvailability;
ALTER TABLE IF EXISTS pt_publish_stock_plans RENAME TO ptStockPlans;
ALTER TABLE IF EXISTS pt_publish_transfer_orders RENAME TO ptTransferOrders;
ALTER TABLE IF EXISTS pt_publish_vendors RENAME TO ptVendors;
ALTER TABLE IF EXISTS pt_publish_work_centers RENAME TO ptWorkCenters;

-- Update sequences
ALTER SEQUENCE IF EXISTS pt_publish_capabilities_id_seq RENAME TO ptCapabilities_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_capacity_interval_resource_assignments_id_seq RENAME TO ptCapacityIntervalResourceAssignments_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_capacity_intervals_id_seq RENAME TO ptCapacityIntervals_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_customers_id_seq RENAME TO ptCustomers_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_departments_id_seq RENAME TO ptDepartments_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_forecast_shipment_inventory_adjustments_id_seq RENAME TO ptForecastShipmentInventoryAdjustments_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_forecast_shipments_id_seq RENAME TO ptForecastShipments_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_forecasts_id_seq RENAME TO ptForecasts_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_inventories_id_seq RENAME TO ptInventories_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_items_id_seq RENAME TO ptItems_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_activities_id_seq RENAME TO ptJobActivities_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_activity_inventory_adjustments_id_seq RENAME TO ptJobActivityInventoryAdjustments_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_material_supplying_activities_id_seq RENAME TO ptJobMaterialSupplyingActivities_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_materials_id_seq RENAME TO ptJobMaterials_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_operation_attributes_id_seq RENAME TO ptJobOperationAttributes_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_operations_id_seq RENAME TO ptJobOperations_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_path_nodes_id_seq RENAME TO ptJobPathNodes_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_paths_id_seq RENAME TO ptJobPaths_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_product_deleted_demands_id_seq RENAME TO ptJobProductDeletedDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_product_forecast_demands_id_seq RENAME TO ptJobProductForecastDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_product_safety_stock_demands_id_seq RENAME TO ptJobProductSafetyStockDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_product_sales_order_demands_id_seq RENAME TO ptJobProductSalesOrderDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_product_transfer_order_demands_id_seq RENAME TO ptJobProductTransferOrderDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_products_id_seq RENAME TO ptJobProducts_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_resource_block_intervals_id_seq RENAME TO ptJobResourceBlockIntervals_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_resource_blocks_id_seq RENAME TO ptJobResourceBlocks_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_resource_capabilities_id_seq RENAME TO ptJobResourceCapabilities_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_resources_id_seq RENAME TO ptJobResources_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_job_successor_manufacturing_orders_id_seq RENAME TO ptJobSuccessorManufacturingOrders_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_jobs_id_seq RENAME TO ptJobs_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_kpis_id_seq RENAME TO ptKpis_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_lots_id_seq RENAME TO ptLots_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_manufacturing_orders_id_seq RENAME TO ptManufacturingOrders_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_master_production_schedule_id_seq RENAME TO ptMasterProductionSchedule_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_metrics_id_seq RENAME TO ptMetrics_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_plant_warehouses_id_seq RENAME TO ptPlantWarehouses_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_plants_id_seq RENAME TO ptPlants_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_product_rules_id_seq RENAME TO ptProductRules_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_pt_attributes_id_seq RENAME TO ptAttributes_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_purchase_to_stock_deleted_demands_id_seq RENAME TO ptPurchaseToStockDeletedDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_purchase_to_stock_forecast_demands_id_seq RENAME TO ptPurchaseToStockForecastDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_purchase_to_stock_inventory_adjustments_id_seq RENAME TO ptPurchaseToStockInventoryAdjustments_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_purchase_to_stock_safety_stock_demands_id_seq RENAME TO ptPurchaseToStockSafetyStockDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_purchase_to_stock_sales_order_demands_id_seq RENAME TO ptPurchaseToStockSalesOrderDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_purchase_to_stock_transfer_order_demands_id_seq RENAME TO ptPurchaseToStockTransferOrderDemands_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_purchases_to_stock_id_seq RENAME TO ptPurchasesToStock_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_recurring_capacity_interval_recurrences_id_seq RENAME TO ptRecurringCapacityIntervalRecurrences_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_recurring_capacity_interval_resource_assignments_id_seq RENAME TO ptRecurringCapacityIntervalResourceAssignments_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_recurring_capacity_intervals_id_seq RENAME TO ptRecurringCapacityIntervals_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_resource_alternate_resources_id_seq RENAME TO ptResourceAlternateResources_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_resource_capabilities_id_seq RENAME TO ptResourceCapabilities_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_resource_scheduled_down_capacities_id_seq RENAME TO ptResourceScheduledDownCapacities_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_resources_id_seq RENAME TO ptResources_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_sales_order_releases_id_seq RENAME TO ptSalesOrderReleases_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_sales_orders_id_seq RENAME TO ptSalesOrders_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_stock_availability_id_seq RENAME TO ptStockAvailability_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_stock_plans_id_seq RENAME TO ptStockPlans_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_transfer_orders_id_seq RENAME TO ptTransferOrders_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_vendors_id_seq RENAME TO ptVendors_id_seq;
ALTER SEQUENCE IF EXISTS pt_publish_work_centers_id_seq RENAME TO ptWorkCenters_id_seq;

COMMIT;

-- Verify the renaming
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND (table_name LIKE 'pt_%' OR table_name LIKE 'ptM%' OR table_name LIKE 'ptJ%' OR table_name LIKE 'ptC%' OR table_name LIKE 'ptR%' OR table_name LIKE 'ptP%')
ORDER BY table_name;