import {
  Calendar,
  Brain,
  Briefcase,
  Database,
  Factory,
  Settings,
  FileText,
  Package,
  Target,
  BarChart3,
  Wrench,
  Shield,
  BookOpen,
  Eye,
  MessageSquare,
  Sparkles,
  Building,
  Server,
  TrendingUp,
  Truck,
  AlertTriangle,
  MessageCircle,
  GraduationCap,
  Monitor,
  Columns3,
  Code,
  Network,
  Globe,
  GitBranch,
  DollarSign,
  Headphones,
  Upload,
  ArrowRightLeft,
  FileSearch,
  Presentation,
  FileX,
  Grid,
  PlayCircle,
  Search,
  History,
  Layout,
  Puzzle,
  AlertCircle,
  Layers,
  Workflow,
  Disc,
  type LucideIcon
} from 'lucide-react';

// Centralized icon registry to avoid repeated object construction
const iconRegistry: Record<string, LucideIcon> = {
  Calendar,
  Brain,
  Briefcase,
  Database,
  Factory,
  Settings,
  FileText,
  Package,
  Target,
  BarChart3,
  Wrench,
  Shield,
  BookOpen,
  Eye,
  MessageSquare,
  Sparkles,
  Building,
  Server,
  TrendingUp,
  Truck,
  AlertTriangle,
  MessageCircle,
  GraduationCap,
  Monitor,
  Columns3,
  Code,
  Network,
  Globe,
  GitBranch,
  DollarSign,
  Headphones,
  Upload,
  ArrowRightLeft,
  FileSearch,
  Presentation,
  FileX,
  Grid,
  PlayCircle,
  Search,
  History,
  Layout,
  Puzzle,
  AlertCircle,
  Layers,
  Workflow,
  Disc
};

/**
 * Get Lucide icon component from icon name
 * @param iconName - Name of the icon to retrieve
 * @returns The Lucide icon component, or FileText as fallback
 */
export function getIconComponent(iconName: string): LucideIcon {
  return iconRegistry[iconName] || FileText;
}

// Export the registry for potential direct access
export { iconRegistry };