-- Table: permissions
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (1, 'dashboard_view', 'dashboard', 'view', 'View dashboard content', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (2, 'dashboard_edit', 'dashboard', 'edit', 'Modify dashboard configuration', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (3, 'production_view', 'production', 'view', 'View production data and schedules', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (4, 'production_control', 'production', 'control', 'Control production processes and scheduling', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (5, 'quality_view', 'quality', 'view', 'View quality metrics and reports', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (6, 'quality_control', 'quality', 'control', 'Manage quality control processes', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (7, 'maintenance_view', 'maintenance', 'view', 'View maintenance schedules and reports', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (8, 'maintenance_manage', 'maintenance', 'manage', 'Manage maintenance operations', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (9, 'admin_access', 'admin', 'all', 'Full administrative access', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (10, 'executive_view', 'executive', 'view', 'View executive-level reports and KPIs', '2025-09-27T18:23:19.845Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (11, 'Sales View', 'sales', 'view', 'View sales information', '2025-10-23T03:09:20.852Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (12, 'Sales Edit', 'sales', 'edit', 'Edit sales information', '2025-10-23T03:09:20.852Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (13, 'Sales Create', 'sales', 'create', 'Create sales orders and quotes', '2025-10-23T03:09:20.852Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (14, 'Customer Service View', 'customer-service', 'view', 'View customer service information', '2025-10-23T03:09:45.287Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (15, 'Customer Service Edit', 'customer-service', 'edit', 'Edit customer service information', '2025-10-23T03:09:45.287Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (16, 'Customer Service Create', 'customer-service', 'create', 'Create customer service tickets', '2025-10-23T03:09:45.287Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (17, 'Workflow Management', 'workflows', 'manage', 'Managing of Workflows', '2025-10-29T17:13:06.268Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (18, 'user-management-view', 'user-management', 'view', 'View and manage users and access control', '2025-10-30T03:43:49.295Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (19, 'getting-started-view', 'getting-started', 'view', 'View getting started guide', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (20, 'business-goals-view', 'business-goals', 'view', 'View business goals', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (21, 'implementation-projects-view', 'implementation-projects', 'view', 'View implementation projects', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (22, 'scheduling-optimizer-view', 'scheduling-optimizer', 'view', 'View scheduling optimizer', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (23, 'production-planning-view', 'production-planning', 'view', 'View production planning', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (24, 'capacity-planning-view', 'capacity-planning', 'view', 'View capacity planning', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (25, 'labor-planning-view', 'labor-planning', 'view', 'View labor planning', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (26, 'optimization-studio-view', 'optimization-studio', 'view', 'View optimization studio', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (27, 'demand-forecasting-view', 'demand-forecasting', 'view', 'View demand forecasting', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (28, 'inventory-optimization-view', 'inventory-optimization', 'view', 'View inventory optimization', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (29, 'analytics-view', 'analytics', 'view', 'View analytics', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (30, 'reports-view', 'reports', 'view', 'View reports', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (31, 'systems-management-view', 'systems-management', 'view', 'View systems management', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (32, 'data-import-view', 'data-import', 'view', 'View data import', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (33, 'systems-integration-view', 'systems-integration', 'view', 'View systems integration', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (34, 'shop-floor-view', 'shop-floor', 'view', 'View shop floor', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (35, 'operator-dashboard-view', 'operator-dashboard', 'view', 'View operator dashboard', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (36, 'forklift-driver-view', 'forklift-driver', 'view', 'View forklift driver', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (37, 'disruption-management-view', 'disruption-management', 'view', 'View disruption management', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (38, 'training-view', 'training', 'view', 'View training', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (39, 'industry-templates-view', 'industry-templates', 'view', 'View industry templates', '2025-10-30T03:49:16.561Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (40, 'constraints-management-view', 'constraints-management', 'view', 'View constraints management', '2025-10-30T03:50:05.164Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (41, 'boards-view', 'boards', 'view', 'View boards', '2025-10-30T03:50:05.164Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (42, 'visual-factory-view', 'visual-factory', 'view', 'View visual factory', '2025-10-30T03:50:05.164Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (43, 'feedback-view', 'feedback', 'view', 'View feedback', '2025-10-30T03:50:05.164Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (44, 'Workflow View', 'workflows', 'view', 'View AI Workflow Automation', '2025-10-30T13:49:38.172Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (46, 'schedule_view', 'schedule', 'view', 'View production schedules and scheduling tools', '2025-10-30T16:39:03.838Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (47, 'schedule_edit', 'schedule', 'edit', 'Edit and modify production schedules', '2025-10-30T16:39:03.838Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (48, 'schedule_manage', 'schedule', 'manage', 'Full control over scheduling features including algorithms', '2025-10-30T16:39:03.838Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (49, 'production_scheduling_view', 'production-scheduling', 'view', 'View production scheduling tools and features', '2025-10-30T16:47:45.904Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (50, 'production_scheduling_edit', 'production-scheduling', 'edit', 'Edit production schedules', '2025-10-30T16:47:45.904Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (51, 'production_scheduling_manage', 'production-scheduling', 'manage', 'Full control over production scheduling', '2025-10-30T16:47:45.904Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (52, 'demand-planning-view', 'demand-planning', 'view', 'View and access demand planning features', '2025-11-03T04:18:43.601Z');
INSERT INTO permissions (id, name, feature, action, description, createdAt) VALUES (53, 'demand-supply-alignment-view', 'demand-supply-alignment', 'view', 'View and access demand-supply alignment features', '2025-11-03T05:29:57.799Z');